/*
 You are given two strings s and t.
String t is generated by random shuffling string s 
and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 
*/

public class LeetCode389 {
    static  public char findTheDifference(String s, String t) {

        // int freq [] = new int[26];
        // for(int i=0;i<t.length();i++){
        //     freq[t.charAt(i)-'a']++;
        // }
        // for(int i=0;i<s.length();i++){
        //     freq[s.charAt(i)-'a']--;
        //     }
        // for(int i=0;i<26;i++){
        //     if(freq[i]==1)return (char)(i+'a');
        // }    
        // return ' ';

        // OR--->

        int ascii_sum = 0;
        for(int i=0;i<t.length();i++){
            ascii_sum += t.charAt(i);
        }
        for(int i=0;i<s.length();i++){
            ascii_sum -= s.charAt(i);
        }
        return (char)ascii_sum;
    }
    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd","abcde"));
    }
}
